[package]
name = "keel-cli"
description = "Keel command-line interface."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[[bin]]
name = "keel"
path = "src/main.rs"

[dependencies]
keel-client = { path = "../keel-client" }
keel-proto = { path = "../keel-proto" }
clap = { version = "4", features = ["derive", "wrap_help"] }
rpassword = "7"
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
